apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reaplet
  namespace: reaplet
  labels:
    app: reaplet
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: reaplet
  namespaceSelector:
    matchNames:
      - reaplet
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
